name:                cav2025-cedar-restrict-gclassroom
version:             0.1.0.0
github:              "githubuser/cav2025-cedar-restrict-gclassroom"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cav2025-cedar-restrict-gclassroom#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- random
- mtl
- list-shuffle
- cmdargs
- typed-process
- bytestring
- utf8-string

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  cav2025-cedar-restrict-gclassroom-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cmdargs
    - cav2025-cedar-restrict-gclassroom

tests:
  cav2025-cedar-restrict-gclassroom-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cav2025-cedar-restrict-gclassroom
